### ISSUE TITLE
Github user-profile vulnerable to broken link hijacking on - https://www.droidsec.org/members/

### ISSUE THREAD

**Issue by priyanshukumar397** [droidsec/droidsec.github.io#92]
Hello Driod Sec Team,

Summary:
On your website, upon going to - https://www.droidsec.org/members/ and under it a researcher named Rex (Security Researcher, Vuln Miner) has his github profile name link left unused so when prompted to his github page link - https://github.com/rex2er it shows 404 error.

Impact:
Any attacker can takeover this username and can point it to their respective github page instead of the actual researcher.

Note: Letting you know if in case this slipped through your eyes.

**Comment by priyanshukumar397** [comment]
**Label: BUG**

**Comment by jduck** [comment]
Thanks. I've removed the dead links to Rex's twitter and github which apparently were both deleted.

**Comment by jduck** [comment]
(Fixed with b1892b60167a318bce1f59c0ce2a059c0ec6c3f3 and 6f880d851a15df13f38af329e38d116e791722e5)

**Comment by priyanshukumar397** [comment]
Thank you @jduck

**Comment by priyanshukumar397** [comment]
**can I also be a member of the community and contribute to driodsec ?**
